### ISSUE TITLE
EOFError during GET request due to broken session file

### ISSUE THREAD

**Issue by mhfowler** [pallets-eco/flask-session#132]
Here is the full error message:
```
Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_session/sessions.py", line 354, in save_session
    total_seconds(app.permanent_session_lifetime))
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/cachelib/file.py", line 147, in set
    self._prune()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/cachelib/file.py", line 96, in _prune
    expires = pickle.load(f)
EOFError: Ran out of input
```

This bug was reported here https://github.com/pallets/flask/issues/2216, but its actually a bug in flask-session I think. 

I was just running into this as well. Its fixed when I deleted all the files in flask_session folder.

**Comment by csm10495** [comment]
Seeing the exact same error as well.

In my case it would appear as though some files are empty... those are likely the ones causing issue: 
```
-rw------- 1 app app      0 Apr 27 01:38 144ccb63d499dfcc5bfb704191c6557e
-rw------- 1 app app      0 Apr 27 01:39 406e0f5ff3f77b4d7af0d09bb0813ea9
-rw------- 1 app app      0 Apr 27 01:39 501b08054fd67fea6e933488e159ee76
-rw------- 1 app app      0 Apr 27 01:38 5202e63715e2e019423315bf57720229
-rw------- 1 app app      0 Apr 27 01:38 5f86049072a3537e87676f2056e7a5f3
-rw------- 1 app app      0 Apr 27 01:39 8a0ccdb61124efb9b59b69091b9713d4
-rw------- 1 app app      0 Apr 27 01:39 a49e8f4a8d67b63464533dec9a74e2e0
-rw------- 1 app app      0 Apr 27 01:38 b00eb809ed8ca40d9c25cd4e9a76a46e
-rw------- 1 app app      0 Apr 27 01:38 b5ff9ad3e48479c15be57cf6355fcf38
-rw------- 1 app app      0 Apr 27 01:38 c89fd52234578d413b2baa3c8b4172dd
-rw------- 1 app app      0 Apr 27 01:38 e234ad3e9171d430eb68c92d21c6567d
```

... and in repr:

```
>>> import pickle
>>> pickle.loads(open('cache/flask_sessions/144ccb63d499dfcc5bfb704191c6557e', 'rb').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
EOFError: Ran out of input
```

**Comment by csm10495** [comment]
Also raised: https://github.com/pallets/cachelib/issues/21 since at the cache layer this could (should) also be handled.

**Comment by Lxstr** [comment]
Closing as seems to be a cachlib error
